version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: paybridge-postgres
    restart: always
    env_file:
      - ./postgres/postgres.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - paybridge_network

networks:
  paybridge_network:
    external: true # Dont forget to create a network manually by using this command <docker network create paybridge_network>

volumes:
  postgres_data:
