version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: paybridge-postgres
    restart: always
    env_file:
      - ./postgres/postgres.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - paybridge_network
  redis:
    image: redis:7
    container_name: paybridge-redis
    restart: always
    ports:
      - "6379:6379"
    env_file:
      - ./redis/redis.env
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - paybridge_network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: paybridge-zookeeper
    restart: always
    env_file:
      - ./zookeeper/zookeeper.env
    ports:
      - "${ZOOKEEPER_CLIENT_PORT}:2181"
    networks:
      - paybridge_network

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: paybridge-kafka
    depends_on:
      - zookeeper
    env_file:
      - ./kafka/kafka.env
    ports:
      - "9092:9092"
      - "29092:29092"
    networks:
      - paybridge_network
      
  # mailhog:
  #   image: mailhog/mailhog:v1.0.1
  #   container_name: paybridge-mailhog
  #   ports:
  #     - "1025:1025"   # SMTP
  #     - "8025:8025"   # Web UI
  #   networks:
  #     - paybridge_network

  # jenkins:
  #   image: jenkins/jenkins:lts
  #   container_name: paybridge-jenkins
  #   user: root
  #   restart: unless-stopped
  #   env_file:
  #     - ./jenkins/jenkins.env
  #   ports:
  #     - "${JENKINS_UI_PORT:-18080}:8080"
  #     - "${JENKINS_AGENT_PORT:-50010}:50000"
  #   volumes:
  #     - jenkins_home:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - paybridge_network
  
  otel-collector:
    image: otel/opentelemetry-collector:0.96.0
    container_name: paybridge-otel-collector
    restart: unless-stopped
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel/otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
    ports:
      - "4317:4317"   # OTLP gRPC (services send here)
    networks:
      - paybridge_network

  jaeger:
    image: jaegertracing/all-in-one:1.55
    container_name: paybridge-jaeger
    restart: unless-stopped
    ports:
      - "16686:16686"   # Jaeger UI
      # - "4317:4317"     # OTLP gRPC
      # - "4318:4318"   # HTTP
    networks:
      - paybridge_network

  prometheus:
    image: prom/prometheus:v2.52.0
    container_name: paybridge-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus:ro
    networks:
      - paybridge_network

  grafana:
    image: grafana/grafana:10.2.0
    container_name: paybridge-grafana
    ports:
      - "3002:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - paybridge_network


  # loki:
  #   image: grafana/loki:2.9.0
  #   container_name: paybridge-loki
  #   restart: unless-stopped
  #   command: -config.file=/etc/loki/loki.yml
  #   volumes:
  #     - ./loki/loki.yml:/etc/loki/loki.yml:ro
  #     - loki_data:/loki
  #   ports:
  #     - "3100:3100"
  #   networks:
  #     - paybridge_network

  # promtail:
  #   image: grafana/promtail:2.9.0
  #   container_name: paybridge-promtail
  #   restart: unless-stopped
  #   command: -config.file=/etc/promtail/promtail.yml
  #   volumes:
  #     - ./promtail/promtail.yml:/etc/promtail/promtail.yml:ro
  #     - paybridge_logs:/var/log/paybridge
  #   networks:
  #     - paybridge_network

  # grafana:
  #   image: grafana/grafana:10.2.0
  #   container_name: paybridge-grafana
  #   restart: unless-stopped
  #   env_file:
  #     - ./grafana/grafana.env
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - ./grafana/datasources:/etc/grafana/provisioning/datasources
  #     - ./grafana/dashboards:/var/lib/grafana/dashboards
  #     - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
  #   networks:
  #     - paybridge_network

volumes:
  postgres_data:
  redis_data:
  jenkins_home:
  grafana_data:
  # loki_data:
  # paybridge_logs:


networks:
  paybridge_network:
    external: true
